import type { ModProfile, ProfileStoreState } from '../types/profiles.js';

// Stato iniziale dello store dei profili
const defaultProfileId = 'default-profile-01';
const profileStoreState: ProfileStoreState = {
  profiles: [
    {
      id: defaultProfileId,
      name: 'Default',
      description: 'Profilo predefinito',
      createdAt: new Date(),
      lastUsed: new Date(),
      modConfiguration: {
        enabledMods: [],
        modOrder: [],
      },
      isActive: true,
      isAutoGenerated: false,
    },
  ],
  activeProfileId: defaultProfileId,
  autoSaveEnabled: true, // Valore predefinito per autoSave
};

/**
 * Restituisce una copia dell'array dei profili.
 * @returns {ModProfile[]} Una copia dell'array dei profili.
 */
export const getProfiles = (): ModProfile[] => {
  return [...profileStoreState.profiles];
};

/**
 * Restituisce l'ID del profilo attivo.
 * @returns {string | null} L'ID del profilo attivo o null se nessuno è attivo.
 */
export const getActiveProfileId = (): string | null => {
  return profileStoreState.activeProfileId;
};

/**
 * Restituisce lo stato di autoSaveEnabled.
 * @returns {boolean} True se l'autoSave è abilitato, false altrimenti.
 */
export const isAutoSaveEnabled = (): boolean => {
  return profileStoreState.autoSaveEnabled;
};

/**
 * Restituisce l'intero stato del ProfileStore.
 * Utile per debugging o per ottenere uno snapshot completo.
 * @returns {ProfileStoreState} Lo stato corrente del ProfileStore.
 */
export const getProfileStoreState = (): ProfileStoreState => {
  // Restituisce una copia profonda per evitare modifiche esterne dirette
  return JSON.parse(JSON.stringify(profileStoreState));
};

/**
 * Aggiorna parzialmente lo stato del ProfileStore.
 * @param {Partial<ProfileStoreState>} newState Un oggetto contenente le chiavi dello stato da aggiornare.
 */
export const updateProfileStoreState = (newState: Partial<ProfileStoreState>): void => {
  Object.assign(profileStoreState, newState);
};

// Esempio di funzioni future (non richieste per questa sotto-task, ma per illustrare l'evoluzione):
// export const addProfile = (profile: ModProfile) => { ... }
// export const setActiveProfile = (profileId: string) => { ... }
// export const toggleAutoSave = () => { ... }

// Non esportare più lo stato direttamente per incoraggiare l'uso delle funzioni.
// export default profileStoreState;