export interface ModProfileConfig {
  enabledMods: string[]; // Array di mod IDs
  modOrder: string[];    // Ordine di caricamento
  settings?: Record<string, any>; // Future: per mod settings
}

export interface ModProfile {
  id: string;
  name: string;
  description?: string;
  createdAt: Date;
  lastUsed: Date;
  modConfiguration: ModProfileConfig;
  isActive: boolean; // Indica se questo è il profilo attualmente applicato al gioco
  isAutoGenerated?: boolean; // Indica se il profilo è stato generato automaticamente (es. auto-save)
}

export interface ProfileStoreState {
  profiles: ModProfile[];
  activeProfileId: string | null;
  autoSaveEnabled: boolean;
}