name: Build and Release Windows

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release-windows: # Nome del job aggiornato per chiarezza
    runs-on: windows-latest # Modificato per eseguire solo su Windows
    permissions:
      contents: write # Necessario per creare release e caricare artefatti

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $version = ("${{ github.ref_name }}" -replace '^v', '').Split('-')[0]
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: | # Aggiornato per usare la versione estratta senza 'v'
            release/${{ steps.get_version.outputs.VERSION }}/*.exe
            release/${{ steps.get_version.outputs.VERSION }}/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}